=== es3649/robo-rally-online/shared/data/board_schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["walls", "spaces", "x_dim", "y_dim", "display_name"],
  "properties": {
    "display_name": {
      "type": "string"
    },
    "walls": {
      "type": "object",
      "required": ["horizontal_walls", "vertical_walls"],
      "properties": {
        "horizontal_walls": {
          "type": "array",
          "maxItems": 12,
          "items": {
            "type": "array",
            "maxItems": 13,
            "items": {
              "type": ["object", "null"],
              "properties": {
                "hi": {
                  "oneOf": [
                    {
                      "type": "string",
                      "enum": ["standard", "laser", "laser2", "laser3"]
                    },{
                      "type": "object",
                      "required": ["registers"],
                      "properties": {
                        "registers": {
                          "type": "array",
                          "items": {
                            "type": "integer"
                          }
                        }
                      }
                    }
                  ]
                },
                "lo": {
                  "oneOf": [
                    {
                      "type": "string",
                      "enum": ["standard", "laser", "laser2", "laser3"]
                    },{
                      "type": "object",
                      "required": ["registers"],
                      "properties": {
                        "registers": {
                          "type": "array",
                          "items": {
                            "type": "integer"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "vertical_walls": {
          "type": "array",
          "maxItems": 13,
          "items": {
            "type": "array",
            "maxItems": 12,
            "items": {
              "type": ["object", "null"],
              "properties": {
                "hi": {
                  "oneOf": [
                    {
                      "type": "string",
                      "enum": ["standard", "laser", "laser2", "laser3"]
                    },{
                      "type": "object",
                      "required": ["registers"],
                      "properties": {
                        "registers": {
                          "type": "array",
                          "items": {
                            "type": "integer"
                          }
                        }
                      }
                    }
                  ]
                },
                "lo": {
                  "oneOf": [
                    {
                      "type": "string",
                      "enum": ["standard", "laser", "laser2", "laser3"]
                    },{
                      "type": "object",
                      "required": ["registers"],
                      "properties": {
                        "registers": {
                          "type": "array",
                          "items": {
                            "type": "integer"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "spaces": {
      "type": "array",
      "maxItems": 12,
      "minItems": 3,
      "items": {
        "type": "array",
        "maxItems": 12,
        "minItems": 3,
        "items": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": ["conv_F", "conv_L", "conv_R", "conv_RF", "conv_LF", "conv_LRF", "conv2_F", "conv2_L", "conv2_R", "conv2_RF", "conv2_LF", "conv2_LRF", "gear_R", "gear_L", "pit", "battery", "spawn"]
            },
            "cover": {
              "oneOf": [
                {
                  "type": "object",
                  "required": ["number"],
                  "properties": {
                    "number": {
                      "type": "integer"
                    }
                  }
                },{
                  "type":"object",
                  "required": ["registers"],
                  "properties": {
                    "registers": {
                      "type": "array",
                      "items": {
                        "type": "integer"
                      }
                    }
                  }
                },{
                  "type": "string",
                  "enum": ["scrambler", "respawn"]
                }
              ]
            },
            "orientation": {
              "type": "string",
              "enum": ["N", "S", "E", "W"]
            },
            "cover_orientation": {
              "type": "string",
              "enum": ["N", "S", "E", "W"]
            }
          }
        }
      }
    },
    "x_dim": {
      "type": "integer"
    },
    "y_dim": {
      "type": "integer"
    }
  }
}

=== es3649/robo-rally-online/shared/data/boards/the_keep.json
{
    "$schema": "../board_schema.json",
    "x_dim": 12,
    "y_dim": 12,
    "display_name": "The Keep",
    "walls": {
        "horizontal_walls": [
            [null,null,null,null,null,{},null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,{},null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,{},null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,{},null,null,null,null,null]
        ],
        "vertical_walls": [
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,{"hi": "laser"},null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,{},null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,{},null,null,null,null,null,null,{},null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,{},null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,{"lo": "laser"},null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null]
        ]
    },
    "spaces": [
        [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ],[
            {},
            {"type": "conv_L","orientation": "S"},
            {"type": "conv_F","orientation": "S"},
            {"type": "conv_F","orientation": "S"},
            {"type": "conv_F","orientation": "S"},
            {"type": "conv_F","orientation": "S"},
            {"type": "conv_F","orientation": "S"},
            {"type": "conv_F","orientation": "S"},
            {"type": "conv_F","orientation": "S"},
            {"type": "conv_F","orientation": "S"},
            {"type": "conv_L","orientation": "W"},
            {}
        ],[
            {},
            {"type": "conv_F","orientation": "E"},
            {"type": "battery"},
            {},
            {},
            {},
            {},
            {},
            {},
            {"type": "battery"},
            {"type": "conv_F","orientation": "W"},
            {}
        ],[
            {},
            {"type": "conv_F","orientation": "E"},
            {},
            {"type": "conv2_L","orientation": "S"},
            {"type": "conv2_F","orientation": "S"},
            {"type": "conv2_F","orientation": "S"},
            {"type": "conv2_F","orientation": "S"},
            {"type": "conv2_F","orientation": "S"},
            {"type": "conv2_L","orientation": "W"},
            {},
            {"type": "conv_F","orientation": "W"},
            {}
        ],[
            {"type": "pit"},
            {"type": "conv_F","orientation": "E"},
            {},
            {"type": "conv2_F","orientation": "E"},
            {"type": "gear_R"},
            {},
            {"type": "pit"},
            {"type": "gear_L"},
            {"type": "conv2_F","orientation": "W"},
            {},
            {"type": "conv_F","orientation": "W"},
            {}
        ],[
            {"type": "conv_F","orientation": "S"},
            {"type": "conv_R","orientation": "E"},
            {},
            {"type": "conv2_F","orientation": "E"},
            {},
            {},
            {},
            {},
            {"type": "conv2_F","orientation": "W"},
            {},
            {"type": "conv_R","orientation": "S"},
            {"type": "conv_F","orientation": "S"}
        ],[
            {"type": "conv_F","orientation": "N"},
            {"type": "conv_R","orientation": "N"},
            {},
            {"type": "conv2_F","orientation": "E"},
            {},
            {},
            {},
            {},
            {"type": "conv2_F","orientation": "W"},
            {},
            {"type": "conv_R","orientation": "W"},
            {"type": "conv_F","orientation": "N"}
        ],[
            {},
            {"type": "conv_F","orientation": "E"},
            {},
            {"type": "conv2_F","orientation": "E"},
            {"type": "gear_L"},
            {"type": "pit"},
            {},
            {"type": "gear_R"},
            {"type": "conv2_F","orientation": "W"},
            {},
            {"type": "conv_F","orientation": "W"},
            {"type": "pit"}
        ],[
            {},
            {"type": "conv_F","orientation": "E"},
            {},
            {"type": "conv2_L","orientation": "E"},
            {"type": "conv2_F","orientation": "N"},
            {"type": "conv2_F","orientation": "N"},
            {"type": "conv2_F","orientation": "N"},
            {"type": "conv2_F","orientation": "N"},
            {"type": "conv2_L","orientation": "N"},
            {},
            {"type": "conv_F","orientation": "W"},
            {}
        ],[
            {},
            {"type": "conv_F","orientation": "E"},
            {"type": "battery"},
            {},
            {},
            {},
            {},
            {},
            {},
            {"type": "battery"},
            {"type": "conv_F","orientation": "W"},
            {}
        ],[
            {},
            {"type": "conv_L","orientation": "E"},
            {"type": "conv_F","orientation": "N"},
            {"type": "conv_F","orientation": "N"},
            {"type": "conv_F","orientation": "N"},
            {"type": "conv_F","orientation": "N"},
            {"type": "conv_F","orientation": "N"},
            {"type": "conv_F","orientation": "N"},
            {"type": "conv_F","orientation": "N"},
            {"type": "conv_F","orientation": "N"},
            {"type": "conv_L","orientation": "N"},
            {}
        ],[
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {}
        ]
    ]
}

=== es3649/robo-rally-online/shared/data/boards/pushy.json
{
  "$schema": "../board_schema.json",
  "x_dim": 12,
  "y_dim": 12,
  "display_name": "Pushy",
  "walls": {
    "horizontal_walls": [
      [null,null,null,null,null,{"hi":{"registers": [3]}},null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null,null,null,null,null,null],
      [null,null,{"lo":{"registers": [1,3,5]}},null,null,null,{"lo":{"registers": [1,3,5]}},null,null,null,{"lo":"laser"},null,null],
      [null,null,null,null,null,null,null,{},null,null,null,null,null],
      [null,null,null,null,null,null,null,null,null,null,null,null,null],
      [null,null,null,null,null,{"hi":{"registers": [2,4]}},null,null,null,{"hi":{"registers": [2,4]}},null,null,null],
      [null,null,null,null,null,null,null,null,{},null,null,null,null],
      [null,null,null,null,{},null,null,null,null,null,null,null,null],
      [null,null,{"lo":{"registers": [2,4]}},null,null,null,{"lo":{"registers": [2,4]}},null,{"lo":{"registers": [1,3,5]}},null,{"lo":{"registers": [2,4]}},null,null],
      [null,null,null,null,null,null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null,null,null,null,null,null]
    ],
    "vertical_walls": [
      [null,null,null,null,null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null,null,null,null,null],
      [null,{"lo":{"registers": [2,4]}},null,{"hi":"laser"},null,{"lo":{"registers": [2,4]}},null,{"hi":{"registers": [1,3,5]}},null,{"lo":{"registers": [2,4]}},null,null],
      [null,null,null,null,null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null,null,null,null,null],
      [{},null,{},null,{},null,null,null,{},null,{},null],
      [null,null,null,null,null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null,null,null,null,null],
      [null,{"hi":{"registers": [1,3,5]}},null,{},null,null,{},null,null,{"hi":{"registers": [1,3,5]}},null,null],
      [null,null,null,null,null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null,null,null,null,null],
      [null,null,null,null,{},null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null,null,null,null,null]
    ]
  },
  "spaces": [
    [
      {},
      {"type": "conv_L","orientation": "N"},
      {"type": "conv_R","orientation": "E"},
      {},
      {},
      {},
      {"type": "pit"},
      {},
      {"type": "conv_F","orientation": "E"},
      {},
      {},
      {}
    ],[
      {},
      {},
      {"type": "conv_L","orientation": "N"},
      {"type": "conv_F","orientation": "N","cover":"scrambler"},
      {"type": "conv_R","orientation": "E"},
      {"type": "gear_R"},
      {"type": "conv_F","orientation": "S"},
      {"type": "conv_F","orientation": "S","cover":"scrambler"},
      {"type": "conv_R","orientation": "S"},
      {},
      {"type": "conv_F","orientation": "S"},
      {"type": "conv_F","orientation": "S"}
    ],[
      {},
      {},
      {},
      {},
      {"type": "conv_F","orientation": "E"},
      {"type": "pit"},
      {"type": "gear_L"},
      {},
      {},
      {},
      {},
      {}
    ],[
      {"type": "conv_R","orientation": "E"},
      {},
      {"type": "battery"},
      {"type": "conv_L","orientation": "E"},
      {"type": "conv_R","orientation": "S"},
      {"type": "conv_F","orientation": "W"},
      {},
      {"type": "conv_L","orientation": "E"},
      {"type": "conv_F","orientation": "S"},
      {},
      {},
      {"type": "gear_R"}
    ],[
      {"type": "conv_L","orientation": "N"},
      {"type": "conv_F","orientation": "N","cover":"scrambler"},
      {"type": "conv_F","orientation": "N"},
      {"type": "conv_RF","orientation": "E"},
      {},
      {"type": "conv_F","orientation": "W","cover":{"registers": [2,5]}},
      {},
      {"type": "conv_F","orientation": "E"},
      {},
      {"type": "battery"},
      {},
      {}
    ],[
      {"type": "conv_F","orientation": "S"},
      {"type": "conv_L","orientation": "S"},
      {"type": "conv_L","orientation": "E"},
      {"type": "conv_R","orientation": "S"},
      {"type": "conv_R","orientation": "N"},
      {"type": "conv_L","orientation": "W"},
      {"type": "conv_L","orientation": "E"},
      {"type": "conv_RF","orientation": "S"},
      {"type": "conv_L","orientation": "S"},
      {},
      {"type": "conv_L","orientation": "E"},
      {"type": "conv_F","orientation": "S"}
    ],[
      {},
      {"type": "conv_F","orientation": "W","cover":"scrambler"},
      {"type": "conv_F","orientation": "E","cover":{"registers": [2,5]}},
      {},
      {"type": "conv_F","orientation": "W","cover":"scrambler"},
      {},
      {"type": "conv_F","orientation": "E"},
      {},
      {"type": "conv_F","orientation": "W","cover":"scrambler"},
      {},
      {"type": "conv_F","orientation": "E","cover":{"registers": [1,3]}},
      {}
    ],[
      {},
      {"type": "conv_R","orientation": "W"},
      {"type": "conv_R","orientation": "S"},
      {},
      {"type": "conv_RF","orientation": "W"},
      {"type": "conv_F","orientation": "S","cover":{"registers": [3,4]}},
      {"type": "conv_R","orientation": "S"},
      {"type": "pit"},
      {"type": "conv_R","orientation": "W"},
      {"type": "conv_F","orientation": "S","cover":{"registers": [2,4]}},
      {"type": "conv_R","orientation": "S"},
      {}
    ],[
      {},
      {"type": "gear_L"},
      {"type": "conv2_L","orientation": "S"},
      {},
      {"type": "conv_F","orientation": "W"},
      {},
      {},
      {},
      {"type": "battery"},
      {},
      {"type": "conv_L","orientation": "E"},
      {"type": "conv_F","orientation": "S"}
    ],[
      {"type": "conv2_F","orientation": "E"},
      {},
      {"type": "conv2_F","orientation": "W"},
      {"type": "battery"},
      {"type": "conv_F","orientation": "W"},
      {},
      {"type": "pit"},
      {},
      {"type": "conv2_F","orientation": "E"},
      {},
      {"type": "conv_F","orientation": "E"},
      {}
    ],[
      {"type": "conv2_F","orientation": "E"},
      {"cover":"scrambler"},
      {"type": "conv2_R","orientation": "W"},
      {"type": "conv2_L","orientation": "S"},
      {},
      {},
      {},
      {"type": "conv2_RF","orientation": "W"},
      {"type": "conv2_R","orientation": "S"},
      {"type": "conv_R","orientation": "W"},
      {"type": "conv_R","orientation": "S"},
      {}
    ],[
      {"type": "conv2_R","orientation": "S"},
      {},
      {},
      {"type": "conv2_F","orientation": "W"},
      {},
      {},
      {},
      {"type": "conv2_R","orientation": "W"},
      {"type": "conv2_F","orientation": "S"},
      {},
      {},
      {}
    ]
  ]
}

=== es3649/robo-rally-online/shared/data/boards/docking_bay_a.json
{
    "$schema": "../board_schema.json",
    "x_dim": 3,
    "y_dim": 12,
    "display_name": "Docking Bay A",
    "walls": {
        "horizontal_walls": [
            [null,null,null,null,{},null,null,null,{},null,null,null,null],
            [null,null,null,null,{},null,null,null,{},null,null,null,null],
            [null,null,null,null,{},null,null,null,{},null,null,null,null]
        ],
        "vertical_walls": [
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null]
        ]
    },
    "spaces": [
        [
            {"type": "spawn"},
            {"type": "spawn"},
            {"type": "spawn"},
            {"type": "spawn"},
            {"type": "spawn"},
            {"type": "spawn"},
            {"type": "spawn"},
            {"type": "spawn"},
            {"type": "spawn"},
            {"type": "spawn"},
            {"type": "spawn"},
            {"type": "spawn"}
        ],[
            {},{},{},{},{},{},{},{},{},{},{},{}
        ],[
            {},{},{},{},{},{},{},{},{},{},{},{}
        ]
    ]
}

=== es3649/robo-rally-online/shared/data/boards/in-and-out.json
{
    "$schema": "../board_schema.json",
    "display_name": "In & Out",
    "x_dim": 12,
    "y_dim": 12,
    "walls": {
        "horizontal_walls": [
            [null,null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,{},null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,{},null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,{},null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,{},null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null,null]
        ],
        "vertical_walls": [
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,{},null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,{},null,null,null,null,{},null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,{},null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null],
            [null,null,null,null,null,null,null,null,null,null,null,null]
        ]
    },
    "spaces": [
        [
            {},
            {"type": "conv2_F","orientation": "E"},
            {},
            {"type": "conv2_F","orientation": "W"},
            {},
            {"type": "conv_R","orientation": "N"},
            {"type": "conv_L","orientation": "W"},
            {},
            {},
            {},
            {},
            {}
        ],[
            {},
            {"type": "conv2_F","orientation": "E"},
            {},
            {"type": "conv2_F","orientation": "W"},
            {},
            {"type": "conv_F","orientation": "W"},
            {"type": "conv2_L","orientation": "E"},
            {"type": "conv2_F","orientation": "S"},
            {"type": "conv2_F","orientation": "S"},
            {"type": "conv2_F","orientation": "S"},
            {"type": "conv2_F","orientation": "S"},
            {"type": "conv2_F","orientation": "S"}
        ],[
            {},
            {"type": "conv2_F","orientation": "E"},
            {},
            {"type": "conv2_F","orientation": "W"},
            {"type": "conv_R","orientation": "N"},
            {"type": "conv_L","orientation": "W"},
            {"type": "conv2_F","orientation": "E"},
            {},
            {"type": "battery"},
            {},
            {},
            {}
        ],[
            {},
            {"type": "conv2_F","orientation": "E"},
            {"type": "battery"},
            {"type": "conv2_F","orientation": "W"},
            {"type": "conv_R","orientation": "W"},
            {"type": "conv_L","orientation": "S"},
            {"type": "conv2_L","orientation": "N"},
            {"type": "conv2_F","orientation": "N"},
            {"type": "conv2_F","orientation": "N"},
            {"type": "conv2_F","orientation": "N"},
            {"type": "conv2_F","orientation": "N"},
            {"type": "conv2_F","orientation": "N"}
        ],[
            {},
            {"type": "conv2_F","orientation": "E"},
            {},
            {"type": "conv2_F","orientation": "W"},
            {},
            {"type": "conv_R","orientation": "W"},
            {"type": "conv_L","orientation": "S"},
            {},
            {},
            {},
            {},
            {}
        ],[
            {"type": "conv_L","orientation": "S"},
            {"type": "conv2_L","orientation": "N"},
            {"type": "conv2_F","orientation": "N"},
            {"type": "conv2_L","orientation": "W"},
            {},
            {},
            {"type": "conv_R","orientation": "W"},
            {"type": "conv_F","orientation": "S"},
            {"type": "conv_F","orientation": "S"},
            {"type": "conv_F","orientation": "S"},
            {"type": "conv_F","orientation": "S"},
            {"type": "conv_F","orientation": "S"}
        ],[
            {"type": "conv_R","orientation": "W"},
            {"type": "conv_F","orientation": "S"},
            {"type": "conv_F","orientation": "S"},
            {"type": "conv_L","orientation": "S"},
            {},
            {},
            {},
            {},
            {"type": "conv2_L","orientation": "E"},
            {"type": "conv2_F","orientation": "S"},
            {"type": "conv2_L","orientation": "S"},
            {}
        ],[
            {},
            {},
            {},
            {"type": "conv_R","orientation": "W"},
            {"type": "conv_F","orientation": "S"},
            {"type": "conv_F","orientation": "S"},
            {"type": "conv_L","orientation": "S"},
            {},
            {"type": "conv2_F","orientation": "E"},
            {},
            {"type": "conv2_F","orientation": "E"},
            {}
        ],[
            {"type": "conv2_F","orientation": "S"},
            {"type": "conv2_F","orientation": "S"},
            {"type": "conv2_F","orientation": "S"},
            {"type": "conv2_F","orientation": "S"},
            {"type": "conv2_F","orientation": "S"},
            {"type": "conv2_L","orientation": "S"},
            {"type": "conv_R","orientation": "W"},
            {"type": "conv_L","orientation": "S"},
            {"type": "conv2_F","orientation": "E"},
            {"type": "battery"},
            {"type": "conv2_F","orientation": "W"},
            {}
        ],[
            {},
            {},
            {},
            {"type": "battery"},
            {},
            {"type": "conv2_F","orientation": "W"},
            {},
            {"type": "conv_F","orientation": "W"},
            {"type": "conv2_F","orientation": "E"},
            {},
            {"type": "conv2_F","orientation": "E"},
            {}
        ],[
            {"type": "conv2_F","orientation": "N"},
            {"type": "conv2_F","orientation": "N"},
            {"type": "conv2_F","orientation": "N"},
            {"type": "conv2_F","orientation": "N"},
            {"type": "conv2_F","orientation": "N"},
            {"type": "conv2_L","orientation": "W"},
            {},
            {"type": "conv_F","orientation": "W"},
            {"type": "conv2_F","orientation": "E"},
            {},
            {"type": "conv2_F","orientation": "E"},
            {}
        ],[
            {},
            {},
            {},
            {},
            {},
            {},
            {"type": "conv_R","orientation": "N"},
            {"type": "conv_L","orientation": "W"},
            {"type": "conv2_F","orientation": "E"},
            {},
            {"type": "conv2_F","orientation": "E"},
            {}
        ]
    ]
}
