=== es3649/robo-rally-online/shared/data/board_schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["walls", "spaces", "x_dim", "y_dim", "display_name"],
  "properties": {
    "display_name": {
      "type": "string"
    },
    "walls": {
      "type": "object",
      "required": ["horizontal_walls", "vertical_walls"],
      "properties": {
        "horizontal_walls": {
          "type": "array",
          "maxItems": 12,
          "items": {
            "type": "array",
            "maxItems": 13,
            "items": {
              "type": ["object", "null"],
              "properties": {
                "hi": {
                  "oneOf": [
                    {
                      "type": "string",
                      "enum": ["standard", "laser", "laser2", "laser3"]
                    },{
                      "type": "object",
                      "required": ["registers"],
                      "properties": {
                        "registers": {
                          "type": "array",
                          "items": {
                            "type": "integer"
                          }
                        }
                      }
                    }
                  ]
                },
                "lo": {
                  "oneOf": [
                    {
                      "type": "string",
                      "enum": ["standard", "laser", "laser2", "laser3"]
                    },{
                      "type": "object",
                      "required": ["registers"],
                      "properties": {
                        "registers": {
                          "type": "array",
                          "items": {
                            "type": "integer"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        },
        "vertical_walls": {
          "type": "array",
          "maxItems": 13,
          "items": {
            "type": "array",
            "maxItems": 12,
            "items": {
              "type": ["object", "null"],
              "properties": {
                "hi": {
                  "oneOf": [
                    {
                      "type": "string",
                      "enum": ["standard", "laser", "laser2", "laser3"]
                    },{
                      "type": "object",
                      "required": ["registers"],
                      "properties": {
                        "registers": {
                          "type": "array",
                          "items": {
                            "type": "integer"
                          }
                        }
                      }
                    }
                  ]
                },
                "lo": {
                  "oneOf": [
                    {
                      "type": "string",
                      "enum": ["standard", "laser", "laser2", "laser3"]
                    },{
                      "type": "object",
                      "required": ["registers"],
                      "properties": {
                        "registers": {
                          "type": "array",
                          "items": {
                            "type": "integer"
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          }
        }
      }
    },
    "spaces": {
      "type": "array",
      "maxItems": 12,
      "minItems": 3,
      "items": {
        "type": "array",
        "maxItems": 12,
        "minItems": 3,
        "items": {
          "type": "object",
          "properties": {
            "type": {
              "type": "string",
              "enum": ["conv_F", "conv_L", "conv_R", "conv_RF", "conv_LF", "conv_LRF", "conv2_F", "conv2_L", "conv2_R", "conv2_RF", "conv2_LF", "conv2_LRF", "gear_R", "gear_L", "pit", "battery", "spawn"]
            },
            "cover": {
              "oneOf": [
                {
                  "type": "object",
                  "required": ["number"],
                  "properties": {
                    "number": {
                      "type": "integer"
                    }
                  }
                },{
                  "type":"object",
                  "required": ["registers"],
                  "properties": {
                    "registers": {
                      "type": "array",
                      "items": {
                        "type": "integer"
                      }
                    }
                  }
                },{
                  "type": "string",
                  "enum": ["scrambler", "respawn"]
                }
              ]
            },
            "orientation": {
              "type": "string",
              "enum": ["N", "S", "E", "W"]
            },
            "cover_orientation": {
              "type": "string",
              "enum": ["N", "S", "E", "W"]
            }
          }
        }
      }
    },
    "x_dim": {
      "type": "integer"
    },
    "y_dim": {
      "type": "integer"
    }
  }
}

=== es3649/robo-rally-online/shared/data/boards/laser_maze.json
{
  "$schema": "../board_schema.json",
  "display_name": "Laser Maze",
  "x_dim": 12,
  "y_dim": 12,
  "walls": {
    "horizontal_walls": [
      [null,{},null,null,null,null,null,null,null,null,{},null,null],
      [null,null,{"hi": "laser"},{},null,null,null,null,null,null,null,null,null],
      [{"hi": "laser"},null,null,null,null,null,null,null,null,null,{},null,{"lo": "laser2"}],
      [null,null,{"hi": "laser"},{},{},{},{},null,null,{},null,null,null],
      [{},null,null,null,null,null,{"hi": "laser2"},{"hi": "laser"},{"hi": "laser2"},null,null,null,{}],
      [null,null,null,null,null,{},null,null,{},null,{},null,null],
      [null,null,null,{},null,null,null,null,null,{"lo": "laser"},null,null,null],
      [{},null,null,null,{},null,{},null,null,null,{"hi": "laser3"},null,{}],
      [null,null,null,{"hi": "laser"},null,{},null,null,{},{"lo": "laser2"},null,null,null],
      [{},null,null,null,null,null,null,null,{},null,null,{},{}],
      [null,null,null,null,null,null,null,null,null,null,null,null,null],
      [null,null,null,null,null,null,null,null,null,{},null,null,null]
    ],
    "vertical_walls": [
      [null,null,{},null,{},null,null,{"hi": "laser2"},null,{},null,null],
      [{},null,null,null,null,null,null,null,null,null,null,{}],
      [null,{},null,null,null,{"hi": "laser"},null,{},null,{},{"lo": {"registers": [2,4]}},null],
      [null,{},null,null,null,null,null,{},null,null,null,null],
      [null,null,null,null,null,null,null,null,{},null,null,null],
      [null,null,null,{},null,null,null,null,{},null,{},null],
      [null,null,null,{"lo":"laser2"},null,null,{},null,null,null,null,null],
      [null,null,null,null,{},null,null,{},null,null,null,null],
      [null,null,null,null,null,null,{},null,null,null,{"hi":"laser2"},null],
      [{"lo":{"registers": [5]}},null,{},null,null,{"hi":"laser2"},null,null,null,null,{},null],
      [null,{"hi":{"registers": [2,4]}},null,null,{},{},null,null,null,{"hi":"laser2"},null,null],
      [null,null,null,null,null,null,null,{"hi":"laser3"},null,null,null,null],
      [null,null,{},null,{"lo":"laser"},null,null,{},null,{},null,null]
    ]
  },
  "spaces": [
    [
      {},
      {"type": "conv_F","orientation": "E"},
      {},
      {},
      {},
      {"type": "conv_F","orientation": "E"},
      {"type": "conv_F","orientation": "W"},
      {},
      {},
      {},
      {"type": "conv_F","orientation": "W"},
      {}
    ],[
      {"type": "conv_F","orientation": "S"},
      {"type": "conv_R","orientation": "E"},
      {},
      {"type": "pit"},
      {"type": "conv_F","orientation": "S"},
      {"type": "conv_R","orientation": "E"},
      {"type": "conv_R","orientation": "S"},
      {"type": "conv_F","orientation": "S"},
      {"type": "conv_F","orientation": "S"},
      {"type": "conv_F","orientation": "S"},
      {"type": "conv_F","orientation": "S"},
      {"type": "conv_F","orientation": "S"}
    ],[
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {}
      ],[
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {"type": "battery"}
    ],[
      {"type": "pit"},
      {"type": "pit"},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {}
    ],[
      {"type": "conv_F","orientation": "S"},
      {"type": "conv_F","orientation": "S"},
      {},
      {},
      {},
      {},
      {},
      {"type": "battery"},
      {},
      {},
      {"type": "pit"},
      {"type": "conv_F","orientation": "S"}
    ],[
      {"type": "conv_F","orientation": "N"},
      {"type": "conv_F","orientation": "N"},
      {"type": "conv_R","orientation": "N"},
      {"type": "conv_R","orientation": "W"},
      {"type": "conv_F","orientation": "N"},
      {"type": "conv_F","orientation": "N"},
      {"type": "conv_F","orientation": "N"},
      {"type": "conv_F","orientation": "N"},
      {"type": "conv_R","orientation": "N"},
      {"type": "conv_R","orientation": "W"},
      {"type": "conv_F","orientation": "N"},
      {"type": "conv_RF","orientation": "N"}
    ],[
      {"type": "pit"},
      {"type": "pit"},
      {"type": "conv_L","orientation": "N"},
      {"type": "conv_L","orientation": "W"},
      {"type": "battery"},
      {},
      {},
      {},
      {"type": "conv_L","orientation": "N"},
      {"type": "conv_L","orientation": "W"},
      {},
      {"type": "conv_F","orientation": "W"}
    ],[
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {"type": "conv_RF","orientation": "W"}
    ],[
      {},
      {},
      {},
      {"type": "pit"},
      {},
      {},
      {},
      {"type": "pit"},
      {},
      {},
      {},
      {"type": "conv_F","orientation": "W"}
    ],[
      {"type": "conv_F","orientation": "N"},
      {"type": "conv_F","orientation": "N"},
      {"type": "conv_F","orientation": "N"},
      {"type": "conv_F","orientation": "N"},
      {"type": "conv_F","orientation": "N"},
      {"type": "conv_R","orientation": "N"},
      {"type": "conv_R","orientation": "W"},
      {"type": "conv_L","orientation": "W"},
      {},
      {},
      {"type": "conv_R","orientation": "W"},
      {"type": "conv_L","orientation": "W"}
    ],[
      {"type": "battery"},
      {"type": "conv_F","orientation": "E"},
      {},
      {},
      {},
      {"type": "conv_F","orientation": "E"},
      {"type": "conv_F","orientation": "W"},
      {},
      {},
      {},
      {"type": "conv_F","orientation": "W"},
      {"type": "pit"}
    ]
  ]
}
